// Generated by CoffeeScript 1.6.2
/*
 jQuery lwao 1.0
 
 Copyright (c) 2013 Helge Söderström
 http://github.com/dimhoLt
 
 Plugin website:
 http://github.com/dimhoLt/lwao_autocomplete
 
 Dual licensed under the MIT and GPL licenses.
 http://en.wikipedia.org/wiki/MIT_License
 http://en.wikipedia.org/wiki/GNU_General_Public_License
 
 Compile through: $ coffee -b -o js -c CoffeeScript/jquery.lwao.coffee
*/
$.fn.extend({
  lwao: function(options) {
    var log, requestTimeout, runAjax, settings;

    settings = {
      minLength: 3,
      ajaxUrl: '',
      ajaxMethod: 'POST',
      ajaxData: {},
      inputVarName: 'searchTerm',
      displayString: ['<span class="quote">%</span></span class="author">by %s</span>', 'quote', 'authorName'],
      selectionValue: 'qid',
      requestWait: 300,
      debug: true
    };
    settings = jQuery.extend(settings, options);
    log = function(msg) {
      if (settings.debug) {
        return typeof console !== "undefined" && console !== null ? console.log(msg) : void 0;
      }
    };
    runAjax = function(query) {
      var ret;

      if (query < settings.minLength) {
        return false;
      }
      ret = {};
      settings.ajaxData.searchTerm = query;
      return $.ajax({
        type: 'POST',
        url: '/ajax/search',
        async: true,
        data: settings.ajaxData,
        success: function(response) {
          return console.log(response);
        },
        error: function(xhr, message, code) {
          return console.log(message);
        },
        complete: function() {}
      });
    };
    requestTimeout = null;
    return $(this).each(function() {
      return $(this).on('keyup', function() {
        if (requestTimeout !== null) {
          clearTimeout(requestTimeout);
        }
        return requestTimeout = setTimeout(runAjax($(this).val()), settings.requestWait);
      });
    });
  }
});
